FROM alpine:latest as build

ARG DOWNLOAD_FILENAME=redbean-original-1.4.com

RUN apk add --update zip bash
RUN wget https://justine.lol/redbean/${DOWNLOAD_FILENAME} -O redbean.com
RUN chmod +x redbean.com

# This will normalize the binary to ELF
RUN zip -d redbean.com .ape
RUN bash /redbean.com -h

# Add your files here
COPY assets /assets
WORKDIR /assets
RUN zip -r /redbean.com *

# just for debugging purposes
RUN ls -la redbean.com
RUN zip -sf redbean.com


FROM scratch

COPY --from=build /redbean.com /
CMD ["/redbean.com", "-vv", "-p", "80"]
