FROM alpine:latest

ARG DOWNLOAD_FILENAME=redbean-original-2.2.com

RUN apk add --update zip
RUN wget https://redbean.dev/${DOWNLOAD_FILENAME} -O redbean.com

RUN chmod +x redbean.com
# normalize the binary to ELF
RUN sh ./redbean.com --assimilate

ONBUILD ARG ASSETS_DIR=assets
ONBUILD COPY ${ASSETS_DIR} /assets
WORKDIR /assets
ONBUILD RUN zip -r /redbean.com *

# just for debugging purposes
ONBUILD RUN ls -la /assets /redbean.com
ONBUILD RUN zip -sf /redbean.com
