FROM alpine:latest as build

ARG DOWNLOAD_FILENAME=redbean-original-tinylinux-2.2.com

RUN apk add --update zip
RUN wget https://redbean.dev/${DOWNLOAD_FILENAME} -O redbean.com

RUN chmod +x redbean.com

RUN ls -la redbean.com
RUN zip -sf redbean.com


FROM scratch

COPY --from=build /redbean.com /
CMD ["/redbean.com", "-vv", "-p", "80"]
